In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/train.csv")
copy_df=df

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=42)

In [ ]:
X_train.shape

(712, 7)

In [ ]:
X_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
from sklearn.impute import KNNImputer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
transformer=ColumnTransformer(
    [
        ('knn',KNNImputer(),[2]),
        ('si',SimpleImputer(strategy='most_frequent'),[6]),
    ],remainder='passthrough')

In [ ]:
X_train_transformed=transformer.fit_transform(X_train)
X_test_transformed=transformer.transform(X_test)

In [ ]:
trans=ColumnTransformer(
    [
        ('ohe',OneHotEncoder(sparse=False),[1]),
        ('ohe1',OneHotEncoder(sparse=False),[3])
    ],remainder='passthrough'
)

In [ ]:
d=pd.DataFrame(X_train_transformed)
c=pd.DataFrame(X_test_transformed)

In [ ]:
X_tt=trans.fit_transform(d)
X_t=trans.transform(c)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [ ]:
dd=pd.DataFrame(X_tt)
cc=pd.DataFrame(X_t)

In [ ]:
dd

       0    1    2    3    4          5  6  7  8        9
0    0.0  0.0  1.0  0.0  1.0       45.5  1  0  0     28.5
1    0.0  0.0  1.0  0.0  1.0       23.0  2  0  0     13.0
2    0.0  0.0  1.0  0.0  1.0       32.0  3  0  0    7.925
3    0.0  0.0  1.0  0.0  1.0       26.0  3  1  0   7.8542
4    0.0  0.0  1.0  1.0  0.0        6.0  3  4  2   31.275
..   ...  ...  ...  ...  ...        ... .. .. ..      ...
707  0.0  0.0  1.0  1.0  0.0       21.0  3  0  0     7.65
708  0.0  0.0  1.0  0.0  1.0  29.498846  1  0  0     31.0
709  0.0  0.0  1.0  0.0  1.0       41.0  3  2  0  14.1083
710  0.0  0.0  1.0  1.0  0.0       14.0  1  1  2    120.0
711  0.0  0.0  1.0  0.0  1.0       21.0  1  0  1  77.2875

[712 rows x 10 columns]

In [ ]:
cc

       0    1    2    3    4          5  6  7  8        9
0    1.0  0.0  0.0  0.0  1.0  29.498846  3  1  1  15.2458
1    0.0  0.0  1.0  0.0  1.0       31.0  2  0  0     10.5
2    0.0  0.0  1.0  0.0  1.0       20.0  3  0  0    7.925
3    0.0  0.0  1.0  1.0  0.0        6.0  2  0  1     33.0
4    1.0  0.0  0.0  1.0  0.0       14.0  3  1  0  11.2417
..   ...  ...  ...  ...  ...        ... .. .. ..      ...
174  0.0  0.0  1.0  0.0  1.0       17.0  3  0  0    7.125
175  1.0  0.0  0.0  0.0  1.0  29.498846  3  0  0    7.225
176  0.0  0.0  1.0  1.0  0.0       38.0  3  1  5  31.3875
177  0.0  0.0  1.0  1.0  0.0       17.0  2  0  0     10.5
178  0.0  0.0  1.0  1.0  0.0        4.0  3  1  1     16.7

[179 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_tt=ss.fit_transform(X_tt)
X_t=ss.transform(X_t)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(max_depth=5,n_estimators=500)

In [ ]:
clf.fit(X_tt,y_train)
y_pred = clf.predict(X_t)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8044692737430168

In [ ]:
y_final=copy_df['Survived']
copy_df.drop(columns=['Survived'],inplace=True)

In [ ]:
copy_df.isnull().sum()

Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
X_final=copy_df

In [ ]:
X_final

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [ ]:
X_final=transformer.fit_transform(X_final)

In [ ]:
X_final

array([[22.0, 'S', 3, ..., 1, 0, 7.25],
       [38.0, 'C', 1, ..., 1, 0, 71.2833],
       [26.0, 'S', 3, ..., 0, 0, 7.925],
       ...,
       [29.69911764705882, 'S', 3, ..., 1, 2, 23.45],
       [26.0, 'C', 1, ..., 0, 0, 30.0],
       [32.0, 'Q', 3, ..., 0, 0, 7.75]], dtype=object)

In [ ]:
xx=pd.DataFrame(X_final)

In [ ]:
X_f=trans.fit_transform(xx)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [ ]:
X_f.shape

(891, 10)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clff=RandomForestClassifier(max_depth=5,n_estimators=500)

In [ ]:
clff.fit(X_f,y_final)

RandomForestClassifier(max_depth=5, n_estimators=500)

In [ ]:
a=pd.read_csv("/content/test.csv")

In [ ]:
a

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
a.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [ ]:
X_ff=transformer.fit_transform(a)

In [ ]:
aa=pd.DataFrame(X_ff)
aa

            0  1  2       3  4  5        6
0        34.5  Q  3    male  0  0   7.8292
1        47.0  S  3  female  1  0      7.0
2        62.0  Q  2    male  0  0   9.6875
3        27.0  S  3    male  0  0   8.6625
4        22.0  S  3  female  1  1  12.2875
..        ... .. ..     ... .. ..      ...
413  30.27259  S  3    male  0  0     8.05
414      39.0  C  1  female  0  0    108.9
415      38.5  S  3    male  0  0     7.25
416  30.27259  S  3    male  0  0     8.05
417  30.27259  C  3    male  1  1  22.3583

[418 rows x 7 columns]

In [ ]:
aa.isnull().sum()
aa=aa.fillna(method='ffill')

In [ ]:
X_x=trans.fit_transform(aa)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [ ]:
X_x.shape

(418, 10)

In [ ]:
predictions=clff.predict(X_x)

In [ ]:
predictions

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [ ]:
titanic_df=pd.read_csv('/content/test.csv')

In [ ]:
final_df=pd.DataFrame(titanic_df['PassengerId'])

In [ ]:
final_df['Survived']=predictions

In [ ]:
final_df

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [ ]:
final_df.to_csv("/content/preds.csv")